eureka:
  client:
    register-with-eureka: false
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/schools/**

        - id: locks
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/locks/**
        - id: users
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/users/**
        - id: messages
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/messages/**
        - id: logs
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/logs/**
        - id: files
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/files/**
            - Path=/files/**

management:
  tracing:
    sampling:
      probability: 1.0
