eureka:
  instance:
    hostname: spring-message-service
  client:
    service-url:
      defaultZone: http://spring-discovery-service:8080/eureka


server:
  port: 8080
spring:
  application:
    name: messages
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/messages
    username: ruibin
    password: ruibin123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: http://rabbitmq
    port: 5672
    username: user
    password: password
    virtual-host: /
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10
        acknowledge-mode: auto
application:
  config:


management:
  tracing:
    sampling:
      probability: 1.0
