application:
  config:
    users-url: http://localhost:8100/api/v1
    locks-url: http://localhost:8300/api/v1
    messages-url: http://localhost:8200/api/v1
    files-url: http://localhost:8400/api/v1
    logs-url: http://localhost:8700/api/v1
    auth-url: http://localhost:8800/api/v1
