application:
  config:
    users-url: http://localhost:8080/api/v1
    locks-url: http://localhost:8080/api/v1
    messages-url: http://localhost:8080/api/v1
    files-url: http://localhost:8080/api/v1
    logs-url: http://localhost:8080/api/v1
    auth-url: http://localhost:8080/api/v1
