eureka:
  instance:
    hostname: spring-user-service
  client:
    service-url:
      defaultZone: http://spring-discovery-service:8080/eureka


server:
  port: 8080
spring:
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/users
    username: ruibin
    password: ruibin123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: http://redis
    port: 6379

application:
  config:
    locks-url: http://spring-lock-service:8080/api/v1/locks
    messages-url: http://spring-message-service:8080/api/v1/messages

management:
  tracing:
    sampling:
      probability: 1.0
