eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8100
spring:
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: ruibin
    password: ruibin123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: 127.0.0.1
    port: 6379

application:
  config:
    locks-url: http://localhost:8222/api/v1/locks
    messages-url: http://localhost:8222/api/v1/messages

management:
  tracing:
    sampling:
      probability: 1.0
